package com.notaskflow.common.enums;

/**
 * 空间实时事件类型。
 *
 * @author LIN
 */
public enum SpaceRealtimeEventType {

    DOCUMENT_CREATED,
    DOCUMENT_UPDATED,
    DOCUMENT_DELETED,
    DOCUMENT_TREE_CHANGED,
    TAG_CREATED,
    TAG_UPDATED,
    TAG_DELETED,
    FILE_CREATED,
    FILE_UPDATED,
    FILE_DELETED,
    FILE_TREE_CHANGED,
    FILE_UPLOAD_CONFIG_UPDATED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    PROJECT_MEMBER_CHANGED,
    TODO_CREATED,
    TODO_UPDATED,
    TODO_DELETED,
    MEMBER_ONLINE,
    MEMBER_OFFLINE,
    SPACE_MEMBER_CHANGED
}
